import { SupportedLanguage } from '../types';

export interface LanguageOption {
  code: SupportedLanguage;
  label: string;
  native: string;
  region: string;
  speechCode: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'hi', label: 'Hindi', native: 'हिन्दी', region: 'North / Central', speechCode: 'hi-IN' },
  { code: 'en', label: 'English', native: 'English', region: 'National', speechCode: 'en-IN' },
  { code: 'bn', label: 'Bengali', native: 'বাংলা', region: 'West Bengal / Tripura', speechCode: 'bn-IN' },
  { code: 'mr', label: 'Marathi', native: 'मराठी', region: 'Maharashtra', speechCode: 'mr-IN' },
  { code: 'te', label: 'Telugu', native: 'తెలుగు', region: 'Andhra Pradesh / Telangana', speechCode: 'te-IN' },
  { code: 'ta', label: 'Tamil', native: 'தமிழ்', region: 'Tamil Nadu', speechCode: 'ta-IN' },
  { code: 'gu', label: 'Gujarati', native: 'ગુજરાતી', region: 'Gujarat', speechCode: 'gu-IN' },
  { code: 'ur', label: 'Urdu', native: 'اُردُو', region: 'National / Telangana / J&K', speechCode: 'ur-IN' },
  { code: 'kn', label: 'Kannada', native: 'ಕನ್ನಡ', region: 'Karnataka', speechCode: 'kn-IN' },
  { code: 'or', label: 'Odia', native: 'ଓଡ଼ିଆ', region: 'Odisha', speechCode: 'or-IN' },
  { code: 'ml', label: 'Malayalam', native: 'മലയാളം', region: 'Kerala', speechCode: 'ml-IN' },
  { code: 'pa', label: 'Punjabi', native: 'ਪੰਜਾਬੀ', region: 'Punjab', speechCode: 'pa-IN' },
  { code: 'as', label: 'Assamese', native: 'অসমীয়া', region: 'Assam', speechCode: 'as-IN' },
  { code: 'mai', label: 'Maithili', native: 'मैथिली', region: 'Bihar / Jharkhand', speechCode: 'hi-IN' },
  { code: 'sat', label: 'Santali', native: 'ᱥᱟᱱᱛᱟᱲᱤ', region: 'Jharkhand / Odisha / WB', speechCode: 'hi-IN' },
  { code: 'ks', label: 'Kashmiri', native: 'کٲشُر', region: 'Jammu & Kashmir', speechCode: 'ur-IN' },
  { code: 'ne', label: 'Nepali', native: 'नेपाली', region: 'Sikkim / West Bengal', speechCode: 'ne-NP' },
  { code: 'kok', label: 'Konkani', native: 'कोंकणी', region: 'Goa / Maharashtra / Karnataka', speechCode: 'mr-IN' },
  { code: 'sd', label: 'Sindhi', native: 'سنڌي / सिन्धी', region: 'Gujarat / Maharashtra / Rajasthan', speechCode: 'sd-IN' },
  { code: 'doi', label: 'Dogri', native: 'डोगरी', region: 'Jammu & Kashmir / HP', speechCode: 'hi-IN' },
  { code: 'mni', label: 'Manipuri', native: 'ꯃꯤꯇែꯢꯂꯣꯟ', region: 'Manipur', speechCode: 'bn-IN' },
  { code: 'brx', label: 'Bodo', native: 'बड़ो', region: 'Assam / Bodoland', speechCode: 'as-IN' },
  { code: 'sa', label: 'Sanskrit', native: 'संस्कृतम्', region: 'Classical / All-India', speechCode: 'hi-IN' },
];

export function getLanguageInfo(code: SupportedLanguage): LanguageOption {
  return SUPPORTED_LANGUAGES.find((l) => l.code === code) || SUPPORTED_LANGUAGES[0];
}

export interface ReportUITranslations {
  dossierTitle: string;
  reportLanguage: string;
  changeLanguage: string;
  translating: string;
  diseaseIdentifiedTitle: string;
  healthyTitle: string;
  severityLabel: string;
  statusLabel: string;
  symptomsObservedTitle: string;
  immediateRemediesTitle: string;
  recommendedVetTitle: string;
  biosecurityTitle: string;
  reproductionAlertsTitle: string;
  pregnancyRiskTitle: string;
  lactationImpactTitle: string;
  contraindicationsTitle: string;
  nutritionalRecommendationTitle: string;
  bodyConditionScoreTitle: string;
  breedBiometricsTitle: string;
  fieldScanLocationTitle: string;
  openMaps: string;
  listenAudio: string;
  stopAudio: string;
  saveDossier: string;
  close: string;
  allLanguages: string;
  searchLanguage: string;
  sufferingFrom?: string;
  healthResult?: string;
  localVernacularName?: string;
  observedSymptomsTitle?: string;
  classifiedBreed?: string;
  coatConditionTitle?: string;
  selectLanguageTitle?: string;
}

export const REPORT_UI_TEXT: Record<string, ReportUITranslations> = {
  en: {
    dossierTitle: 'Clinical Diagnostic Dossier & Pathology Report',
    reportLanguage: 'Report Language',
    changeLanguage: 'Change Language',
    translating: 'Translating report...',
    diseaseIdentifiedTitle: 'Disease Identified & Clinical Diagnosis',
    healthyTitle: 'Animal Health Status: Normal & Healthy',
    severityLabel: 'Severity Grade',
    statusLabel: 'Clinical Status',
    symptomsObservedTitle: 'Symptoms Observed on Cattle',
    immediateRemediesTitle: 'Immediate First-Aid Remedies (Farmer Protocol)',
    recommendedVetTitle: 'Recommended Veterinary Actions',
    biosecurityTitle: 'Biosecurity & Quarantine Protocol',
    reproductionAlertsTitle: 'Reproductive & Lactation Health Alerts',
    pregnancyRiskTitle: 'Gestation Safety & Handling',
    lactationImpactTitle: 'Milk Yield & Mastitis Risk',
    contraindicationsTitle: 'Critical Drug Contraindications',
    nutritionalRecommendationTitle: 'Targeted Nutritional Recommendation',
    bodyConditionScoreTitle: 'Body Condition Score (BCS)',
    breedBiometricsTitle: 'Biometrics & Breed Assessment',
    fieldScanLocationTitle: 'Scanned Cattle Location',
    openMaps: 'Open in Maps',
    listenAudio: 'Listen to Diagnosis',
    stopAudio: 'Stop Audio',
    saveDossier: 'Save Formal Dossier',
    close: 'Close Report',
    allLanguages: 'All 23 Constitutional Languages',
    searchLanguage: 'Search language or script...',
  },
  hi: {
    dossierTitle: 'नैदानिक ​​रोग निदान डोजियर एवं विकृति विज्ञान रिपोर्ट',
    reportLanguage: 'रिपोर्ट की भाषा',
    changeLanguage: 'भाषा बदलें',
    translating: 'रिपोर्ट का अनुवाद हो रहा है...',
    diseaseIdentifiedTitle: 'पशु में पहचाना गया रोग व निदान',
    healthyTitle: 'पशु स्वास्थ्य स्थिति: सामान्य व स्वस्थ',
    severityLabel: 'गंभीरता स्तर',
    statusLabel: 'रोग स्थिति',
    symptomsObservedTitle: 'पशु पर देखे गए प्रमुख लक्षण',
    immediateRemediesTitle: 'तत्काल प्राथमिक उपचार (किसान के लिए प्रोटोकॉल)',
    recommendedVetTitle: 'पशु चिकित्सक द्वारा अनुशंसित उपचार',
    biosecurityTitle: 'जैव-सुरक्षा एवं संगरोध (क्वारंटीन) नियम',
    reproductionAlertsTitle: 'प्रजनन एवं दुग्ध उत्पादन चेतावनी',
    pregnancyRiskTitle: 'गर्भावस्था सुरक्षा एवं देखभाल',
    lactationImpactTitle: 'दूध उत्पादन प्रभाव व थनैला जोखिम',
    contraindicationsTitle: 'निषेध दवाइयां (जो नहीं देनी हैं)',
    nutritionalRecommendationTitle: 'विशेष पोषण एवं आहार सलाह',
    bodyConditionScoreTitle: 'शारीरिक स्थिति स्कोर (BCS)',
    breedBiometricsTitle: 'नस्ल एवं बायोमेट्रिक विश्लेषण',
    fieldScanLocationTitle: 'स्कैन किए गए पशु का वास्तविक स्थान',
    openMaps: 'मानचित्र में देखें',
    listenAudio: 'निदान सुनें (ऑडियो)',
    stopAudio: 'आवाज रोकें',
    saveDossier: 'डोजियर सुरक्षित करें',
    close: 'रिपोर्ट बंद करें',
    allLanguages: 'सभी 23 संवैधानिक भाषाएं',
    searchLanguage: 'भाषा या लिपि खोजें...',
  },
  gu: {
    dossierTitle: 'રોગ નિદાન ડોઝિયર અને પશુ સ્વાસ્થ્ય અહેવાલ',
    reportLanguage: 'અહેવાલની ભાષા',
    changeLanguage: 'ભાષા બદલો',
    translating: 'અહેવાલનું ભાષાંતર થઈ રહ્યું છે...',
    diseaseIdentifiedTitle: 'પશુમાં ઓળખાયેલ રોગ અને નિદાન',
    healthyTitle: 'પશુ સ્વાસ્થ્ય સ્થિતિ: સામાન્ય અને તંદુરસ્ત',
    severityLabel: 'તીવ્રતા સ્તર',
    statusLabel: 'રોગ સ્થિતિ',
    symptomsObservedTitle: 'પશુ પર જોવા મળેલા મુખ્ય લક્ષણો',
    immediateRemediesTitle: 'તાત્કાલિક પ્રાથમિક સારવાર (ખેડૂત માટે પગલાં)',
    recommendedVetTitle: 'પશુચિકિત્સક દ્વારા ભલામણ કરેલ સારવાર',
    biosecurityTitle: 'જૈવ-સુરક્ષા અને ક્વોરેન્ટાઇન નિયમો',
    reproductionAlertsTitle: 'સંવર્ધન અને દૂધ ઉત્પાદન સાવચેતી',
    pregnancyRiskTitle: 'ગર્ભાવસ્થા સંભાળ અને સુરક્ષા',
    lactationImpactTitle: 'દૂધ ઉત્પાદન પર અસર અને મસ્ટાઇટિસ જોખમ',
    contraindicationsTitle: 'પ્રતિબંધિત દવાઓ (જે ન આપવી)',
    nutritionalRecommendationTitle: 'વિશેષ આહાર અને પોષણ ભલામણ',
    bodyConditionScoreTitle: 'શારીરિક સ્થિતિ સ્કોર (BCS)',
    breedBiometricsTitle: 'નસલ અને બાયોમેટ્રિક મૂલ્યાંકન',
    fieldScanLocationTitle: 'પશુ સ્કેન કરેલ વાસ્તવિક સ્થળ',
    openMaps: 'નકશામાં જુઓ',
    listenAudio: 'અહેવાલ સાંભળો (ઓડિયો)',
    stopAudio: 'અવાજ બંધ કરો',
    saveDossier: 'અહેવાલ સાચવો',
    close: 'અહેવાલ બંધ કરો',
    allLanguages: 'તમામ ૨૩ બંધારણીય ભાષાઓ',
    searchLanguage: 'ભાષા શોધો...',
  },
  mr: {
    dossierTitle: 'वैद्यकीय रोग निदान अहवाल आणि पॅथॉलॉजी डॉसियर',
    reportLanguage: 'अहवालाची भाषा',
    changeLanguage: 'भाषा बदला',
    translating: 'अहवालाचे भाषांतर होत आहे...',
    diseaseIdentifiedTitle: 'जनावरामध्ये आढळलेला रोग व निदान',
    healthyTitle: 'पशु आरोग्य स्थिती: सामान्य व निरोगी',
    severityLabel: 'तीव्रता पातळी',
    statusLabel: 'रोग स्थिती',
    symptomsObservedTitle: 'जनावरावर आढळलेली प्राथमिक लक्षणे',
    immediateRemediesTitle: 'तात्काळ प्रथमोपचार (शेतकऱ्यांसाठी उपाय)',
    recommendedVetTitle: 'पशुवैद्यकीय अधिकाऱ्यांची उपचार शिफारस',
    biosecurityTitle: 'जैव-सुरक्षा आणि विलगीकरण नियम',
    reproductionAlertsTitle: 'प्रजनन आणि दुग्ध उत्पादन सूचना',
    pregnancyRiskTitle: 'गाभण जनावराची काळजी आणि सुरक्षितता',
    lactationImpactTitle: 'दूध उत्पादनावरील परिणाम व कासदाह धोका',
    contraindicationsTitle: 'वर्ज्य औषधे (जी देऊ नयेत)',
    nutritionalRecommendationTitle: 'विशेष पोषण व खाद्य शिफारस',
    bodyConditionScoreTitle: 'शारीरिक स्थिती गुण (BCS)',
    breedBiometricsTitle: 'जात आणि बायोमेट्रिक तपासणी',
    fieldScanLocationTitle: 'तपासणी केलेले प्रत्यक्ष ठिकाण',
    openMaps: 'नकाशावर पहा',
    listenAudio: 'निदान ऐका (ऑडिओ)',
    stopAudio: 'आवाज थांबवा',
    saveDossier: 'अहवाल जतन करा',
    close: 'अहवाल बंद करा',
    allLanguages: 'सर्व २३ संविधानिक भाषा',
    searchLanguage: 'भाषा शोधा...',
  },
  bn: {
    dossierTitle: 'ক্লিনিকাল রোগ নির্ণয় ডসিয়ার এবং প্যাথলজি রিপোর্ট',
    reportLanguage: 'রিপোর্টের ভাষা',
    changeLanguage: 'ভাষা পরিবর্তন করুন',
    translating: 'রিপোর্ট অনুবাদ করা হচ্ছে...',
    diseaseIdentifiedTitle: 'শনাক্তকৃত রোগ ও ক্লিনিকাল ডায়াগনোসিস',
    healthyTitle: 'পশুর স্বাস্থ্য অবস্থা: স্বাভাবিক ও সুস্থ',
    severityLabel: 'তীব্রতার মাত্রা',
    statusLabel: 'রোগের অবস্থা',
    symptomsObservedTitle: 'পশুতে পরিলক্ষিত লক্ষণসমূহ',
    immediateRemediesTitle: 'তাত্ক্ষণিক প্রাথমিক চিকিৎসা (কৃষকের করণীয়)',
    recommendedVetTitle: 'পশুচিকিৎসকের প্রস্তাবিত ব্যবস্থা',
    biosecurityTitle: 'বায়োসিকিউরিটি ও কোয়ারেন্টাইন নিয়মাবলী',
    reproductionAlertsTitle: 'প্রজনন ও দুগ্ধ উৎপাদন সতর্কতা',
    pregnancyRiskTitle: 'গর্ভাবস্থার নিরাপত্তা ও যত্ন',
    lactationImpactTitle: 'দুধ উৎপাদনে প্রভাব ও ওলানফোলা ঝুঁকি',
    contraindicationsTitle: 'নিষিদ্ধ ওষুধ (যা ব্যবহার করবেন না)',
    nutritionalRecommendationTitle: 'পুষ্টি ও খাদ্য সংক্রান্ত পরামর্শ',
    bodyConditionScoreTitle: 'শারীরিক অবস্থা স্কোর (BCS)',
    breedBiometricsTitle: 'জাত ও বায়োমেট্রিক মূল্যায়ন',
    fieldScanLocationTitle: 'পশু স্ক্যান করার আসল অবস্থান',
    openMaps: 'মানচিত্রে দেখুন',
    listenAudio: 'রোগ নির্ণয় শুনুন (অডিও)',
    stopAudio: 'অডিও বন্ধ করুন',
    saveDossier: 'ডসিয়ার সংরক্ষণ করুন',
    close: 'রিপোর্ট বন্ধ করুন',
    allLanguages: 'সমস্ত ২৩টি সাংবিধানিক ভাষা',
    searchLanguage: 'ভাষা খুঁজুন...',
  },
  pa: {
    dossierTitle: 'ਪਸ਼ੂ ਰੋਗ ਨਿਦਾਨ ਡੋਜ਼ੀਅਰ ਅਤੇ ਪੈਥੋਲੋਜੀ ਰਿਪੋਰਟ',
    reportLanguage: 'ਰਿਪੋਰਟ ਦੀ ਭਾਸ਼ਾ',
    changeLanguage: 'ਭਾਸ਼ਾ ਬਦਲੋ',
    translating: 'ਰਿਪੋਰਟ ਦਾ ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ...',
    diseaseIdentifiedTitle: 'ਪਸ਼ੂ ਵਿੱਚ ਪਛਾਣੀ ਗਈ ਬਿਮਾਰੀ ਅਤੇ ਨਿਦਾਨ',
    healthyTitle: 'ਪਸ਼ੂ ਸਿਹਤ ਸਥਿਤੀ: ਆਮ ਅਤੇ ਤੰਦਰੁਸਤ',
    severityLabel: 'ਗੰਭੀਰਤਾ ਪੱਧਰ',
    statusLabel: 'ਬਿਮਾਰੀ ਦੀ ਸਥਿਤੀ',
    symptomsObservedTitle: 'ਪਸ਼ੂ ਉੱਤੇ ਦੇਖੇ ਗਏ ਮੁੱਖ ਲੱਛਣ',
    immediateRemediesTitle: 'ਤੁਰੰਤ ਮੁੱਢਲਾ ਇਲਾਜ (ਕਿਸਾਨ ਲਈ ਉਪਾਅ)',
    recommendedVetTitle: 'ਪਸ਼ੂ ਡਾਕਟਰ ਦੁਆਰਾ ਸਿਫ਼ਾਰਸ਼ ਕੀਤਾ ਇਲਾਜ',
    biosecurityTitle: 'ਜੈਵ-ਸੁਰੱਖਿਆ ਅਤੇ ਵੱਖ ਰੱਖਣ ਦੇ ਨਿਯਮ',
    reproductionAlertsTitle: 'ਪ੍ਰਜਨਨ ਅਤੇ ਦੁੱਧ ਉਤਪਾਦਨ ਚੇਤਾਵਨੀ',
    pregnancyRiskTitle: 'ਗਰਭ ਅਵਸਥਾ ਦੀ ਸੁਰੱਖਿਆ ਅਤੇ ਦੇਖਭਾਲ',
    lactationImpactTitle: 'ਦੁੱਧ ਉਤਪਾਦਨ ਉੱਤੇ ਅਸਰ ਅਤੇ ਮਸਟਾਇਟਿਸ ਖਤਰਾ',
    contraindicationsTitle: 'ਮਨਾਹੀ ਵਾਲੀਆਂ ਦਵਾਈਆਂ (ਜੋ ਨਹੀਂ ਦੇਣੀਆਂ)',
    nutritionalRecommendationTitle: 'ਖ਼ਾਸ ਖੁਰਾਕੀ ਸਿਫ਼ਾਰਸ਼',
    bodyConditionScoreTitle: 'ਸਰੀਰਕ ਸਥਿਤੀ ਸਕੋਰ (BCS)',
    breedBiometricsTitle: 'ਨਸਲ ਅਤੇ ਬਾਇਓਮੈਟ੍ਰਿਕ ਵਿਸ਼ਲੇਸ਼ਣ',
    fieldScanLocationTitle: 'ਸਕੈਨ ਕੀਤੇ ਗਏ ਪਸ਼ੂ ਦਾ ਅਸਲ ਸਥਾਨ',
    openMaps: 'ਨਕਸ਼ੇ ਵਿੱਚ ਦੇਖੋ',
    listenAudio: 'ਨਿਦਾਨ ਸੁਣੋ (ਆਡੀਓ)',
    stopAudio: 'ਆਵਾਜ਼ ਬੰਦ ਕਰੋ',
    saveDossier: 'ਰਿਪੋਰਟ ਸਾਂਭੋ',
    close: 'ਰਿਪੋਰਟ ਬੰਦ ਕਰੋ',
    allLanguages: 'ਸਾਰੀਆਂ 23 ਸੰਵਿਧਾਨਕ ਭਾਸ਼ਾਵਾਂ',
    searchLanguage: 'ਭਾਸ਼ਾ ਲੱਭੋ...',
  },
  te: {
    dossierTitle: 'క్లినికల్ రోగ నిర్ధారణ నివేదిక మరియు పాథాలజీ డాసియర్',
    reportLanguage: 'నివేదిక భాష',
    changeLanguage: 'భాషను మార్చండి',
    translating: 'నివేదిక అనువదించబడుతోంది...',
    diseaseIdentifiedTitle: 'గుర్తించబడిన వ్యాధి మరియు రోగ నిర్ధారణ',
    healthyTitle: 'పశువుల ఆరోగ్య స్థితి: సాధారణం & ఆరోగ్యకరం',
    severityLabel: 'తీవ్రత స్థాయి',
    statusLabel: 'వ్యాధి స్థితి',
    symptomsObservedTitle: 'పశువులో కనిపించిన ముఖ్య లక్షణాలు',
    immediateRemediesTitle: 'తక్షణ ప్రథమ చికిత్స (రైతుల నివారణలు)',
    recommendedVetTitle: 'పశువైద్యుల సిఫార్సు చికిత్స',
    biosecurityTitle: 'జీవ రక్షణ మరియు క్వారంటైన్ నిబంధనలు',
    reproductionAlertsTitle: 'సంతానోత్పత్తి మరియు పాల దిగుబడి హెచ్చరికలు',
    pregnancyRiskTitle: 'గర్భధారణ భద్రత మరియు సంరక్షణ',
    lactationImpactTitle: 'పాల దిగుబడిపై ప్రభావం & పొదుగువాపు ప్రమాదం',
    contraindicationsTitle: 'నిషిద్ధ మందులు (వాడకూడనివి)',
    nutritionalRecommendationTitle: 'లక్ష్య పోషకాహార సిఫార్సు',
    bodyConditionScoreTitle: 'శరీర స్థితి స్కోరు (BCS)',
    breedBiometricsTitle: 'జాతి మరియు బయోమెట్రిక్ విశ్లేషణ',
    fieldScanLocationTitle: 'పశువును స్కాన్ చేసిన ఖచ్చితమైన ప్రదేశం',
    openMaps: 'మ్యాప్‌లో చూడండి',
    listenAudio: 'నిర్ధారణ వినండి (ఆడియో)',
    stopAudio: 'ఆడియో ఆపండి',
    saveDossier: 'నివేదికను సేవ్ చేయండి',
    close: 'నివేదికను మూసివేయండి',
    allLanguages: 'అన్ని 23 రాజ్యాంగ భాషలు',
    searchLanguage: 'భాషను శోధించండి...',
  },
  ta: {
    dossierTitle: 'மருத்துவ நோய் கண்டறிதல் அறிக்கை மற்றும் நோயியல் ஆவணம்',
    reportLanguage: 'அறிக்கை மொழி',
    changeLanguage: 'மொழியை மாற்றவும்',
    translating: 'அறிக்கை மொழிபெயர்க்கப்படுகிறது...',
    diseaseIdentifiedTitle: 'கண்டறியப்பட்ட நோய் மற்றும் பரிசோதனை',
    healthyTitle: 'கால்நடை ஆரோக்கிய நிலை: இயல்பானது & ஆரோக்கியமானது',
    severityLabel: 'தீவிரத்தன்மை நிலை',
    statusLabel: 'நோயின் நிலை',
    symptomsObservedTitle: 'கால்நடையில் காணப்பட்ட முக்கிய அறிகுறிகள்',
    immediateRemediesTitle: 'உடனடி முதலுதவி சிகிச்சை (விவசாயிகளுக்கான வழிகாட்டல்)',
    recommendedVetTitle: 'கால்நடை மருத்துவர் பரிந்துரைக்கும் சிகிச்சைகள்',
    biosecurityTitle: 'உயிரியல் பாதுகாப்பு மற்றும் தனிமைப்படுத்தல் நெறிமுறை',
    reproductionAlertsTitle: 'இனப்பெருக்கம் மற்றும் பால் உற்பத்தி எச்சரிக்கை',
    pregnancyRiskTitle: 'சினைப்பாதுகாப்பு மற்றும் பராமரிப்பு',
    lactationImpactTitle: 'பால் உற்பத்தி தாக்கம் & மடிநோய் அபாயம்',
    contraindicationsTitle: 'தடைசெய்யப்பட்ட மருந்துகள் (பயன்படுத்தக்கூடாதவை)',
    nutritionalRecommendationTitle: 'ஊட்டச்சத்து மற்றும் தீவனப் பரிந்துரை',
    bodyConditionScoreTitle: 'உடல் நிலை மதிப்பீடு (BCS)',
    breedBiometricsTitle: 'இனம் மற்றும் உயிரியல் அளவீடு',
    fieldScanLocationTitle: 'கால்நடை ஸ்கேன் செய்யப்பட்ட உண்மையான இடம்',
    openMaps: 'வரைபடத்தில் பார்க்கவும்',
    listenAudio: 'பரிசோதனையைக் கேளுங்கள் (ஆடியோ)',
    stopAudio: 'ஆடியோவை நிறுத்து',
    saveDossier: 'ஆவணத்தைச் சேமிக்கவும்',
    close: 'அறிக்கையை மூடவும்',
    allLanguages: 'அனைத்து 23 அரசியலமைப்பு மொழிகள்',
    searchLanguage: 'மொழியைத் தேடுங்கள்...',
  },
  kn: {
    dossierTitle: 'ವೈದ್ಯಕೀಯ ರೋಗನಿರ್ಣಯ ವರದಿ ಮತ್ತು ರೋಗಶಾಸ್ತ್ರ ದಾಖಲೆ',
    reportLanguage: 'ವರದಿಯ ಭಾಷೆ',
    changeLanguage: 'ಭಾಷೆ ಬದಲಾಯಿಸಿ',
    translating: 'ವರದಿ ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ...',
    diseaseIdentifiedTitle: 'ಗುರುತಿಸಲಾದ ರೋಗ ಮತ್ತು ರೋಗನಿರ್ಣಯ',
    healthyTitle: 'ಪ್ರಾಣಿ ಆರೋಗ್ಯ ಸ್ಥಿತಿ: ಸಾಮಾನ್ಯ ಮತ್ತು ಆರೋಗ್ಯಕರ',
    severityLabel: 'ತೀವ್ರತೆಯ ಮಟ್ಟ',
    statusLabel: 'ರೋಗದ ಸ್ಥಿತಿ',
    symptomsObservedTitle: 'ಪ್ರಾಣಿಯಲ್ಲಿ ಕಂಡುಬಂದ ಮುಖ್ಯ ಲಕ್ಷಣಗಳು',
    immediateRemediesTitle: 'ತಕ್ಷಣದ ಪ್ರಥಮ ಚಿಕಿತ್ಸಾ ಕ್ರಮಗಳು (ರೈತರಿಗೆ ಪರಿಹಾರಗಳು)',
    recommendedVetTitle: 'ಪಶುವೈದ್ಯರ ಶಿಫಾರಸು ಚಿಕಿತ್ಸೆಗಳು',
    biosecurityTitle: 'ಜೈವಿಕ ಸುರಕ್ಷತೆ ಮತ್ತು ಪ್ರತ್ಯೇಕತೆಯ ನಿಯಮಗಳು',
    reproductionAlertsTitle: 'ಸಂತಾನೋತ್ಪತ್ತಿ ಮತ್ತು ಹಾಲು ಇಳುವರಿ ಎಚ್ಚರಿಕೆ',
    pregnancyRiskTitle: 'ಗರ್ಭಧಾರಣೆ ಸುರಕ್ಷತೆ ಮತ್ತು ಕಾಳಜಿ',
    lactationImpactTitle: 'ಹಾಲು ಇಳುವರಿ ಪರಿಣಾಮ ಮತ್ತು ಕೆಚ್ಚಲುಬಾವು ಅಪಾಯ',
    contraindicationsTitle: 'ನಿಷೇಧಿತ ಔಷಧಗಳು (ನೀಡಬಾರದು)',
    nutritionalRecommendationTitle: 'ವಿಶೇಷ ಪೋಷಕಾಂಶ ಮತ್ತು ಆಹಾರ ಶಿಫಾರಸು',
    bodyConditionScoreTitle: 'ದೇಹ ಸ್ಥಿತಿ ಸ್ಕೋರ್ (BCS)',
    breedBiometricsTitle: 'ತಳಿ ಮತ್ತು ಬಯೋಮೆಟ್ರಿಕ್ ಮೌಲ್ಯಮಾಪನ',
    fieldScanLocationTitle: 'ಸ್ಕ್ಯಾನ್ ಮಾಡಿದ ನಿಖರ ಸ್ಥಳ',
    openMaps: 'ನಕ್ಷೆಯಲ್ಲಿ ವೀಕ್ಷಿಸಿ',
    listenAudio: 'ರೋಗನಿರ್ಣಯ ಆಲಿಸಿ (ಆಡಿಯೋ)',
    stopAudio: 'ಆಡಿಯೋ ನಿಲ್ಲಿಸಿ',
    saveDossier: 'ವರದಿ ಉಳಿಸಿ',
    close: 'ವರದಿ ಮುಚ್ಚಿ',
    allLanguages: 'ಎಲ್ಲಾ 23 ಸಾಂವಿಧಾನಿಕ ಭಾಷೆಗಳು',
    searchLanguage: 'ಭಾಷೆ ಹುಡುಕಿ...',
  },
  ml: {
    dossierTitle: 'ക്ലിനിക്കൽ രോഗനിർണയ റിപ്പോർട്ടും പാത്തോളജി രേഖയും',
    reportLanguage: 'റിപ്പോർട്ടിന്റെ ഭാഷ',
    changeLanguage: 'ഭാഷ മാറ്റുക',
    translating: 'റിപ്പോർട്ട് വിവർത്തനം ചെയ്യുന്നു...',
    diseaseIdentifiedTitle: 'കണ്ടെത്തിയ രോഗവും രോഗനിർണയവും',
    healthyTitle: 'കന്നുകാലി ആരോഗ്യ നില: സാധാരണവും ആരോഗ്യകരവും',
    severityLabel: 'തീവ്രത നില',
    statusLabel: 'രോഗാവസ്ഥ',
    symptomsObservedTitle: 'കന്നുകാലിയിൽ കണ്ട പ്രധാന ലക്ഷണങ്ങൾ',
    immediateRemediesTitle: 'ഉടനടി പ്രഥമശുശ്രൂഷ (കർഷകർക്കുള്ള പ്രതിവിധികൾ)',
    recommendedVetTitle: 'വെറ്ററിനറി ഡോക്ടറുടെ ചികിത്സാ നിർദ്ദേശങ്ങൾ',
    biosecurityTitle: 'ബയോസെക്യൂരിറ്റിയും ഐസൊലേഷൻ പ്രോട്ടോക്കോളും',
    reproductionAlertsTitle: 'പ്രജനന, പാൽ ഉത്പാദന മുന്നറിയിപ്പുകൾ',
    pregnancyRiskTitle: 'ഗർഭധാരണ സംരക്ഷണവും പരിചരണവും',
    lactationImpactTitle: 'പാൽ ഉത്പാദനത്തിലെ കുറവും അകിടുവീക്ക സാധ്യതയും',
    contraindicationsTitle: 'നൽകാൻ പാടില്ലാത്ത മരുന്നുകൾ',
    nutritionalRecommendationTitle: 'പ്രത്യേക പോഷകാഹാര നിർദ്ദേശം',
    bodyConditionScoreTitle: 'ശരീര സ്ഥിതി സ്കോർ (BCS)',
    breedBiometricsTitle: 'ഇനവും ബയോമെട്രിക് വിലയിരുത്തലും',
    fieldScanLocationTitle: 'സ്കാൻ ചെയ്ത യഥാർത്ഥ സ്ഥലം',
    openMaps: 'മാപ്പിൽ കാണുക',
    listenAudio: 'രോഗനിർണയം കേൾക്കുക (ഓഡിയോ)',
    stopAudio: 'ഓഡിയോ നിർത്തുക',
    saveDossier: 'റിപ്പോർട്ട് സൂക്ഷിക്കുക',
    close: 'റിപ്പോർട്ട് അടയ്ക്കുക',
    allLanguages: 'എല്ലാ 23 ഭരണഘടനാ ഭാഷകളും',
    searchLanguage: 'ഭാഷ തിരയുക...',
  },
  ur: {
    dossierTitle: 'طبی تشخیص اور پیتھالوجی تفصیلی رپورٹ',
    reportLanguage: 'رپورٹ کی زبان',
    changeLanguage: 'زبان تبدیل کریں',
    translating: 'رپورٹ کا ترجمہ ہو رہا ہے...',
    diseaseIdentifiedTitle: 'جانور میں شناخت شدہ بیماری اور تشخیص',
    healthyTitle: 'جانوروں کی صحت کی حالت: نارمل اور تندرست',
    severityLabel: 'شدت کا درجہ',
    statusLabel: 'بیماری کی حالت',
    symptomsObservedTitle: 'مویشی پر دیکھی گئی نمایاں علامات',
    immediateRemediesTitle: 'فوری ابتدائی طبی امداد (کسان کے لیے اقدامات)',
    recommendedVetTitle: 'ماہر حیوانات کے تجویز کردہ اقدامات',
    biosecurityTitle: 'بائیو سیکیورٹی اور قرنطینہ کے ضوابط',
    reproductionAlertsTitle: 'افزائش اور دودھ کی پیداوار کے انتباہات',
    pregnancyRiskTitle: 'حمل کی حفاظت اور دیکھ بھال',
    lactationImpactTitle: 'دودھ کی پیداوار پر اثرات اور تھنوں کی سوزش کا خطرہ',
    contraindicationsTitle: 'ممنوعہ ادویات (جو نہیں دینی ہیں)',
    nutritionalRecommendationTitle: 'خصوصی خوراک اور غذائیت کی سفارش',
    bodyConditionScoreTitle: 'جسمانی حالت کا اسکور (BCS)',
    breedBiometricsTitle: 'نسل اور بایومیٹرک جائزہ',
    fieldScanLocationTitle: 'جانور کی جانچ کا اصل مقام',
    openMaps: 'نقشے میں دیکھیں',
    listenAudio: 'تشخیص سنیں (آڈیو)',
    stopAudio: 'آڈیو بند کریں',
    saveDossier: 'رپورٹ محفوظ کریں',
    close: 'رپورٹ بند کریں',
    allLanguages: 'تمام 23 آئینی زبانیں',
    searchLanguage: 'زبان تلاش کریں...',
  },
};

export function getReportUIText(lang: string): ReportUITranslations {
  return REPORT_UI_TEXT[lang] || REPORT_UI_TEXT['hi'] || REPORT_UI_TEXT['en'];
}
